language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
sudo: required
services: docker
before_install:
  - git clone https://github.com/GETLIMS/LIMS-Backend.git
  - cd LIMS-Backend
  - LOCAL_BRANCH=$TRAVIS_BRANCH
  - (git branch -a | egrep "remotes/origin/${LOCAL_BRANCH}\$" ) || LOCAL_BRANCH=dev
  - git checkout $LOCAL_BRANCH
  - docker create -v /var/lib/postgresql/data --name db_data postgres:latest /bin/echo "Data only container for DB"
  - docker run -d --name db --volumes-from db_data postgres:latest
  - docker build --no-cache -t getlims/backend .
  - docker run -t --link db:db getlims/backend python manage.py migrate
  - docker run -t --link db:db getlims/backend python manage.py runscript create_superuser
  - docker run -t --link db:db getlims/backend python manage.py createinitialrevisions
  - docker run -p 8000:8000 --link db:db --name app -d getlims/backend
  - cd ..
before_script:
  - npm install
  - npm install -g grunt-cli bower
  - bower install
  - gem install compass
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
