sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
# TODO Set up a test backend server for the frontend to communicate with during tests
  - 'npm install'
  - 'npm install -g grunt-cli bower'
  - 'bower install'
  - 'gem install compass'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
